INSERT INTO users (id, name, last_name, type) VALUES (1, 'Juan', 'Pérez', 0);
INSERT INTO users (id, name, last_name, type) VALUES (2, 'María', 'González', 0);
INSERT INTO users (id, name, last_name, type) VALUES (3, 'Carlos', 'López', 0);
INSERT INTO users (id, name, last_name, type) VALUES (4, 'Ana', 'Ramírez', 0);
INSERT INTO users (id, name, last_name, type) VALUES (5, 'Pedro', 'Sánchez', 0);
INSERT INTO users (id, name, last_name, type) VALUES (6, 'Sofía', 'Díaz', 0);
INSERT INTO users (id, name, last_name, type) VALUES (7, 'Luis', 'Martínez', 0);
INSERT INTO users (id, name, last_name, type) VALUES (8, 'Fernanda', 'Hernández', 0);
INSERT INTO users (id, name, last_name, type) VALUES (9, 'Diego', 'García', 0);
INSERT INTO users (id, name, last_name, type) VALUES (10, 'Valentina', 'Muñoz', 0);

INSERT INTO courses (id, name, description, price) VALUES (1, 'Introducción a la Programación', 'Curso introductorio sobre los conceptos fundamentales de la programación.', 99.99);
INSERT INTO courses (id, name, description, price) VALUES (2, 'Bases de Datos y SQL', 'Aprende a diseñar y administrar bases de datos utilizando el lenguaje SQL.', 129.99);
INSERT INTO courses (id, name, description, price) VALUES (3, 'Desarrollo web con HTML y CSS', 'Aprende a crear páginas web utilizando HTML para la estructura y CSS para el diseño.', 79.99);
INSERT INTO courses (id, name, description, price) VALUES (4, 'Algoritmos y Estructuras de Datos', 'Curso avanzado sobre algoritmos y estructuras de datos para resolver problemas eficientemente.', 149.99);
INSERT INTO courses (id, name, description, price) VALUES (5, 'Programación Orientada a Objetos', 'Aprende los principios y técnicas de la programación orientada a objetos.', 109.99);
INSERT INTO courses (id, name, description, price) VALUES (6, 'Redes de Computadoras', 'Curso sobre los fundamentos de las redes de computadoras y protocolos de comunicación.', 89.99);
INSERT INTO courses (id, name, description, price) VALUES (7, 'Seguridad Informática', 'Aprende a proteger sistemas y datos contra amenazas y ataques cibernéticos.', 139.99);
INSERT INTO courses (id, name, description, price) VALUES (8, 'Inteligencia Artificial', 'Curso que introduce los conceptos y aplicaciones de la inteligencia artificial.', 169.99);
INSERT INTO courses (id, name, description, price) VALUES (9, 'Desarrollo de Aplicaciones Móviles', 'Aprende a crear aplicaciones móviles para dispositivos iOS y Android.', 119.99);
INSERT INTO courses (id, name, description, price) VALUES (10, 'Análisis de Datos con Python', 'Curso que enseña técnicas de análisis y visualización de datos utilizando Python.', 99.99);